# Generated by Django 5.2 on 2025-05-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0002_usuario_alter_servidor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorIntentos',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('contador', models.PositiveIntegerField()),
                ('ultimo_intento', models.DateTimeField()),
            ],
        ),
    ]
