# Generated by Django 5.2 on 2025-05-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0003_contadorintentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
