# Generated by Django 5.2 on 2025-07-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0004_remove_usuario_id_usuario_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='nombre',
            field=models.CharField(default='ServidorDesconocido', max_length=100),
        ),
    ]
