version: '3.8'

services:
   app:
      #image: nigga
      build: ./nigga
      volumes:
         - ./nigga/proyecto:/code
      depends_on:
         - bd
      environment:
         SECRET_KEY: ${SECRET_KEY}
         DB_ENGINE: 'django.db.backends.mysql' 
         DB_NAME: ${DB_NAME}
         DB_USER: ${DB_USER}
         DB_PASSWORD: ${DB_PASSWORD}
         DB_HOST: bd
         DB_PORT: ${DB_PORT}
         TOKEN_BOT: ${TOKEN_BOT}
         RECAPTCHA_PUBLIC_KEY: ${RECAPTCHA_PUBLIC_KEY}
         RECAPTCHA_PRIVATE_KEY: ${RECAPTCHA_PRIVATE_KEY}
      deploy:
         resources:
            limits:
               cpus: "1"
               memory: "1024M"

   bd:
      image: mysql:8.0
      restart: always
      environment:
         MYSQL_USER: ${DB_USER}
         MYSQL_PASSWORD: ${DB_PASSWORD}
         MYSQL_DATABASE: ${DB_NAME}
         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      volumes:
         - ./data:/var/lib/mysql
      ports:
        - 3308:3306
      deploy:
         resources:
            limits:
               cpus: "1"
               memory: "1024M"
   nginx:
      image: nginx
      restart: always
      ports:
         - 80:80
         - 443:443
      volumes:
         - ./nginx:/etc/nginx/conf.d
         - ./nigga/proyecto/servidores/static:/static
         - ./certificados:/certs
         - ./nginx.conf:/etc/nginx/nginx.conf:ro
      deploy:
         resources:
            limits:
               cpus: "1"
               memory: "1024M"
